### ISSUE TITLE
Readme changes

### ISSUE THREAD

**Issue by KoleckOLP** [KoleckOLP/yt-dl#12]
- [x] I could not set default tab on Pekpek's PC,
- [x] ReEncode is now shared yes
- [x] Add cookies support to cli (add cookies to config) #7 
- [x] Add option to keep cover when converting to mp3
- [x] Fix list version crashing if dependency missing #13

- More to write down as I find.

**Comment by KoleckOLP** [comment]
Now is time to test debug and release

**Comment by KoleckOLP** [comment]
## tasks to do before release:
- [ ] All done updating the readme
- [ ] Update pictures to reflect the new design
- [ ] Write a warning message about HaikuOS support
- [ ] Write a small how to get cookies.txt
- [ ] Update requirements
- [ ] Update How to install if required

**Comment by KoleckOLP** [comment]
this should be done :D

**Comment by KoleckOLP** [comment]
this is way overdue

**Comment by KoleckOLP** [comment]
Too messy too old, closing for now.
